# Anmol inspired by athul waka-stats
name: Update Gist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Daytime-Gist
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          GIST_ID: ${{ vars.DAYTIME_GIST_ID }}
          SHOW_COMMIT: true
          SHOW_LANGUAGE: false

          SYMBOL_VERSION: 2
          SHOW_SHORT_INFO: false
          SHOW_LINE_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          DEBUG_LOGGING: false

      - name: Update Lang-Gist
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          GIST_ID: ${{ vars.LANG_GIST_ID }}
          SHOW_COMMIT: false
          SHOW_LANGUAGE: true

          SYMBOL_VERSION: 2
          SHOW_SHORT_INFO: false
          SHOW_LINE_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          DEBUG_LOGGING: false